apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolrider-web
  namespace: schoolrider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schoolrider-web
  template:
    metadata:
      labels:
        app: schoolrider-web
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: schoolrider-web

      containers:
      - name: schoolrider-web
        image: ghcr.io/harris-consult/schoolrider-landing:latest
        ports:
        - containerPort: 9011
        envFrom:
        - secretRef:
            name: schoolrider-secrets

        volumeMounts:
        - name: files
          mountPath: /usr/src/app/files_upload

      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: schoolrider-web-files
